import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

export default function Home() {
  return (
    <div className="min-h-screen h-full w-full flex flex-col bg-brand-light overflow-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="min-w-full text-gray-800 py-14 px-4 md:px-0">
        <div className="flex items-center container mx-auto max-w-5xl justify-between">
          {/* logo */}
          <Link href="#">
            <a className="font-Exo text-xl md:text-3xl font-bold">
              <span className="bg-gradient-to-br from-brand-blue to-brand-green  pr-2 bg-clip-text text-transparent">
                Bored Ape
              </span>
            </a>
          </Link>
        </div>
      </header>
      <div className="h-full container max-w-5xl mx-auto flex flex-col items-center pt-4">
        <div className="flex flex-col items-center max-w-4xl w-full">
          <Link href="/mint" passHref>
            <a className="mt-16 font-Exo uppercase inline-flex items-center px-6 py-2 text-sm md:text-2xl font-medium text-center rounded-lg bg-gray-100 text-brand-red hover:bg-brand-red hover:text-gray-100 hover:rounded-full ">
              Go to minting page
            </a>
          </Link>
        </div>
      </div>
    </div>
  )
}
